baseURL = ""
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
canonifyurls  = true
languageCode = "fa"
DefaultContentLanguage = "fa"
title = "Composites Collective"
theme = "gohugo-theme-ananke"


MetaDataFormat = "yaml"
SectionPagesMenu = "main"
Paginate = 15 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  languageDirection = "ltr"
  description = "Composites Collective operates at the intersection of design & technology, behavioral sciences, and society."
  facebook = ""
  twitter = "compositescollective"
  instagram = ""
  youtube = ""
  background_color_class = "bg-white"
